# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TPw6Hbsr93dqgBeVtg9PBC7auluKwLIA/Z/A/sFRL5m+VAea0UicUXO2ml2telfR+qGkRxl6wM6h7ILRiAoUBYqUPcSeMveuzyPPGcjXPOaRZTDCqMzziQyj7F+haNusRu+2GqF3oFJI4W6gLOCZ07XxA3jeeqfA6rERVyPJI+i+ymM+Tw5iCOEGAmPvsTW+MAuy3iUrxAUQrIA52XHPvwu5sCCxRPIvF1n8ehAWWbHbKNs3apFBebTtYnR9ml6GSh7qAAogc++E50CDFsMvHfNhDRuqL+pxPSHiIr3UIGfuEqgDRpe2+yr/Mo7rpjzWsCuqq4/z+bjMoBJ0B83UZnQWYr8y27IMYMEKpDndj6/e5mtoyqwet0hJbGYTirz5g2xLT/5Pq3nFfGnEATDq9OQRww+SVZowPquOVwRInjoRls7qGB3+WbsJGS/nLuXW35IB0yiD2J2MkKojti/F3BqZBLWFmePGNb5EiBErIIP3EyF5kD09obuwOXsidFVnEXwIEjUMbZ0oFXwgJnUrFAwC5Yf59nv5bV0TQ+h3rlOYdLdQOILK907aS8mgpHZ6uGFLubUPij8Kfboi0yYwlxDfi9EY4b9CVr0XhjY9vIuqvWd5wYRbUuQUm0Q6FjETP+mI+zTnn11oWTAy/ZuN8Fc3KXwPb+NPy13bVXbiGRc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml