travis:
  secure:
    BINSTAR_TOKEN: gBNEw3UY6aVW4MjgfK27nk2POgtbMdImvtJDT6up0OntGg3w31xZG44jhX4qtwX8t/iHt4Dtvh7rohystabLM6CvZbfWZ6JSoG8zUMoXBngTcCZKbCvy3o4fLDEDaGY00t8bbzRtLR2R7dNSYMsUYCQ3bKK3ietuAYvBZvARYfZAoZqBwNDcVGNcxywSq7XjlxlihxqKhDqS8P9Z2GLSBVNpOOZ4giW2WTRYmDLBgcBmGT9A6zNC7TQz4QVhLRP3w2u8XIHiC/qR8f7rSCaoiwpX9GyjLBKHOXAgXiTqekFtRWRK6e9Vwt6NntNepLxlYe35xWpjPgtnMxe94ff5ocXQqdcx/cGzGrtLBnE8BOYImVWaINKlMtCtpceglXkhQ6ukbhvCCvSvy5HD8BLsk8eVHzERKbZxfMe2dVoIqR1jXp59U0cO0Jnutboa7q4Ug70Y4OY8feHKWQy0p1a49PKBLkb7Hfe2krW/uZ7bxWxs1eVsUgqODWlfj5C9pQ5I8R5pq6K0AsilVUk7N2151wLErRL1EyRarcYDCOsa3GHeOniAm4TSNdLAa/osBQbLRnhvwYs8gXyfsMuFOwoR76Hz5FoLMKiIswzixEvgTnkgCdd/PWKyazoGTn4QR4/is8KRKHEWZ5Yj3ZKYiXS8tNA7DW2NceVGTEt2QQ94qd8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
