travis:
  secure:
    BINSTAR_TOKEN: l2YIQSnVQ5GcOQTj36XP1IpxxQK9GPZJ8hBLjadWq/uvua4TgQIiP23Dw0DeIk7xQiKbidEht+yKT/ZYip7u0/PM6wfPG5PEfgKuA+ptr46mWUrGifzrMczjKbdOjYdzU0pMrvcbXIEn+TtFUTx6PwrK1vdu4h9cGEfeuz3/bVn95UYd7Q0wYoQ6fHbKqsviqJ4rz9h+sce7C3jk/oIDXs6DwEdzeQHqNpFIu1yjX7CbhmRtGScPZ+CExo8MLcoi189ELjeA/pyPCh3zDh8BPjX66d3iA9pjWVWAqU+8qEsQB99IPBG6Zyj6jROYXdW2nOQJABt/pJ9flD1g/s1jg5aif/r97EFHAs3vgSOSZHzCoJZ5IxWZkbNSxi+Dwmv5xMre2dlpAL59dgMLDdTxFhETgCNWlxOj8C+8Eh0twMo7tlsLftEYa9Ji525uzF0paM+lx627k/o2IbuHtgUQFNTp5RCkwUnzOVO/0Cvgw6SbOZeBznkKt+f8Ksg085vRdY48aA7pMzlZxnv7+Omr/BBYXygSsUQY0go7IlpdjczVrHIXOFkMK8lF5GQkjRKcozK8fzR74C+iwy5XFyX8KNCzWD20U0lZkDBLueLKLKnsSf7w6R/PVA5ktqwO9FCGob9/vIvQDN49IORgY7a3FIlOm7F3xQJ2tH6c+nWNujo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
