travis:
  secure:
    BINSTAR_TOKEN: JMcAfZYvOfe8HpydV4Wetq9cqmR/fBITPnjKKnG0YAGnlhzUYhzd5nDaA+g7hAFEp8ufAUruqk+CwY+jud+Rc4ry9vkE0xrWI1aDFeDuD0MGdnnbgskFB0RkFpdt6SQqzdJJm18f2sL2eMNn7Vi1vE319MmVNNXVlnb6PzHZSNtahKb323gdWd5FnsngJD9uXNv4u4pnGwxw3SGwONtYNiBHW37Yh0By5LgkEb+Tlw7XyncgDh1gE5L4hJJE/poMVYqYNLXAL14ZIbsTjrv6TkGiUFt2d+xN17LSUw70kaX2E1LtfUgmMvnZ6gzd+Mn8/Fgfth34HIM4kFF4ZEpT1pnT1ApqBmFGzlD1qQvq6/PPj8iMsEq2SvozrbHw01AkhE1oxKNFNuCOnzSQ/bNSMDPd8EPSxF8oAOGMimI+2Qd9+77Cw9l3Z+Gw+w+3XQyfhUG0j/LQMe/Uilpd1ArZV/kqOZoylHnKmmdR2wVVUfsKq2fGJw45SfbgtroGqKns4pyjz5c+ETglf4Pa0WiOTkUYHiTg3DszCrh3jBGpHr3Onh/Lh2IfB2pg/tTbJJRFZWSbMFtl6RLhTxjnKnpXcDEvMe9V/oXyx4TnTRKyQSWyo1eDeaD3WdrhCUhBZX+Btfrt+XeFs+wyP44pkDyU6B9tqgXOa89yzXhqvScWWvk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
