travis:
  secure:
    BINSTAR_TOKEN: nh6wnF7zcqapnROtx1UgHPHLR/INXnPmh3FjdGtAYD6KdDuvFnfR3LGlmU8XVJTOXmg8F43bEbFJys28G/pQuT2wC9CgYMqwyS8h4J00aQtbaxF8P3u/Hb/WVCuj1dxeqK025cI5GUnIn0ktz3/mji//p/51K2pL1XYt8Cw+rTqirGIKOaYkkvce0nHee7fnnXPQwfgaKuIBUzYqVmfT0aZQkaeM/cf36bdKKtjaFfbUW1OYiY1dJc2wnUB4WE1nl/QrQHZOggP/vfz+H/4oWsb3kLXNN7X9+aidKqCbcHwtQ3BryyRkMDPpBatK9s6su/mXkG407xVTcRVklxPMTRPV08II639/KAZxsuIqslpr4aSwnPyK3T2YfZNeQ35CCC8w2c2xwBMwvyi0nv8l19INVr0v6C+SHM/awBMIYJWRU47FPa3hpLZ+rpba5ZSU6StJD95ugyreI57CXfaFu5wYbhsWAThO6Y4Dm3WQPIUvONlk2S8u97n7LtPL02T6ZlFyzpV/aAde/n3WuW/olOI8mslaQ/VqKu30r4NsQotFTpqqA8KNyJ8CwUz631XPSBtk28aM/koboUVKPtaj2v+znODFJJCYqMXi8OFbzwceog8NCwSoTD0e/Qxk50g63UMpownTQgyRKcidg3XbHhze5u1MT4A8hFNiyCvlXv8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
