travis:
  secure:
    BINSTAR_TOKEN: hCWoMUKKXvuieDu6SsVKUGNcPLMU4A3JezzIN2P4mYT/Voyyxpg8/iDZ9nl5+lNAb0KAgAllattP/t+eIMBouRAq0+WfzK5VmktNEImxbue6N6FmIFw4azJFGO04b1D/Lkju8wYdmKY8XoqbBMCfScpvoi8VChB8estWG8WJzRkOLMceBSTnXgkscrUcDNyztfd0AHplGM7upoftRQVdT7mgmRVYLuyT8miNdKhLYvMJ3wLS1deR2e+JG0X6sR2JFB6dhP8oIoZE4/UT+0ejxV9fXGbEvcLxyn+/omfS4EX0rOXlq6cjizS2mMPG1wCU93Q9J8H/PXl8v9Sw7pG+M2/zbEBW4Ly9oBv6meNX+oH6SMxhli9D8HgQe+BksvPYropMY7hPPazPpSNtt9cdbMZA4r1WTWprgvsbGYIFslpcQnlDGfxiiIjcJ2HsIahANrdwiXIYlqi4aMuJwOvboJWm5xUCzakkboWYFdl06JRYYNEc4NrMSVIauxQvSZngrQ+HrQPFL8Nf0tUvx2HaGo6+MbhEa117bHuLVDXs/QYkgCXxStDobSDYdtikZBe5iSdC0c82YprUcybu58sElg7+G1oPafFIemY0XfutD+AvAEo3oFjgT6cKTXh6SHgvNgV641BC9lr9/hmFQB4ifnwNuV2ZnLi000BLf2dAfaM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
