travis:
  secure:
    BINSTAR_TOKEN: VX4p1okrJReqNu6rqWXiYlLXMSxNGxrj+PTU01ai84iVmNUHGP28aCGOjMlir8l/ms84INO36g+a4uM3EaMXSnnPVmP3yKq2sx00/dWQf24aLiEAcvHYLac1riABEf8PE1oVCm4uXgZex8Aa5hNXvNxA1wNgghPMQdhRhFZ5bVEBOT/OqWNvMVSLF2gHx/F2GfVYh02/VNaEBizH8UsLVyJurVFFh90lbaRvPOmu1YUtJbBbqKlRlo2RYx1RXgwQXH5lpzYhpXg4tFxpak6ok/79OZz2i1zPuSeotgqRkKIUAgnRvY8POCIoeB1EkjZEKwpbat59G2z1M1t9mvwhzI8aTHsxS+HGEe0t6jwPHc1g+2al6DrLApzq93dzElusvjLidzZPuGGLNzNbhL12ZdCc2Gbt6Sqw2EKVmY22Co6OwdmnZsWqBwt87LBqgvzRlLvxDBlS6wOBWF+iwAZIUJgBYvRRCyPBOrVjkusSfhF2z8bxBtMkrVpaKljHC1wifb9XHhPdyqCHd6uGlSLw5p9DBccY3PZj8/7jIZjiNX23SlSc52sBzJz6FfA1uFn21SRrBQEXI+8AutGA9CwjyaULz2ApsPHcncgNuM9mFTnE0jFeYHrzafBRAve3S3ShUIhI/GmBMtZI82S27wbKt41aA1hbhxstANF6WB+4l38=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
