travis:
  secure:
    BINSTAR_TOKEN: abrdHU/4pdd06WF3dgO3QYFkxxqt7McbZ55/EhJ6Y/R4oZDEyeYH81vFWi2zVm2DF+BdaDThZWLXr6Am9LaZj0+MyesX1bQIvFFPYM7YQfLwGLk6r9Nm/XeU8yInUhGDTacnQXvP69GyFo8TBb/H7NAso5hXtV1NTqFBYHjf/0w5xmDSfsjrdoPAV0hzpPJmV+D6P5trpVtUFE9L06HMSrWCN+Kk32R45kZpTIJPHoUpZ5bYhkK/lhha809GoxWbxTX9BFA1aGq/iS4UQnIHYYyi7cOjw1+ZqDG4cueNeLwqpgi7IQ57R//22+KVuEliB9rtyK7I91pFA1zDppJ/Nly7dmodInq2G2BaXDfSi6vpPz54NCvX/NaVKBuUUU+Ae8o7cUyhT+vpF+fATGkjFCOjqs6lE8rPPrHu2uDOHW26jMwDku/TmrkcwHBqqyXAzZfulwzTzVB++UL31+2R6WM+ORcxyQOLiAl4e1UuwEJ2V7bjsG+cAD1qvNv6iy9jC1+gtWRl2DpAiP7tQKmj7KMS6iP4WKKn5O6bu8nd2pztYwgcmctNgD5xl25l/N1w4oTOpIpPiNDLWCjGwAxPZVhWMYnn4wCcjnH64x49pzVbTP5NaSkKAti8Ib4dSTmfjOSsV6prq4xKjOgQKX6rYwbFWg0t5+kQFU228pUu+jU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
