travis:
  secure:
    BINSTAR_TOKEN: TPw6Hbsr93dqgBeVtg9PBC7auluKwLIA/Z/A/sFRL5m+VAea0UicUXO2ml2telfR+qGkRxl6wM6h7ILRiAoUBYqUPcSeMveuzyPPGcjXPOaRZTDCqMzziQyj7F+haNusRu+2GqF3oFJI4W6gLOCZ07XxA3jeeqfA6rERVyPJI+i+ymM+Tw5iCOEGAmPvsTW+MAuy3iUrxAUQrIA52XHPvwu5sCCxRPIvF1n8ehAWWbHbKNs3apFBebTtYnR9ml6GSh7qAAogc++E50CDFsMvHfNhDRuqL+pxPSHiIr3UIGfuEqgDRpe2+yr/Mo7rpjzWsCuqq4/z+bjMoBJ0B83UZnQWYr8y27IMYMEKpDndj6/e5mtoyqwet0hJbGYTirz5g2xLT/5Pq3nFfGnEATDq9OQRww+SVZowPquOVwRInjoRls7qGB3+WbsJGS/nLuXW35IB0yiD2J2MkKojti/F3BqZBLWFmePGNb5EiBErIIP3EyF5kD09obuwOXsidFVnEXwIEjUMbZ0oFXwgJnUrFAwC5Yf59nv5bV0TQ+h3rlOYdLdQOILK907aS8mgpHZ6uGFLubUPij8Kfboi0yYwlxDfi9EY4b9CVr0XhjY9vIuqvWd5wYRbUuQUm0Q6FjETP+mI+zTnn11oWTAy/ZuN8Fc3KXwPb+NPy13bVXbiGRc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
