travis:
  secure:
    BINSTAR_TOKEN: Ib2k38UKpIk6X2acrpk+PVgdsgcXf11ZXElwNkdx1i47FNxuvO9CIrUir439lqZW3ZzBD0M/TFJxDpWpNiMXXzclLmDQD7foP8tB/1ZtC8dJtWUq7RD0cN2ur819Hm8t8Zpko4KfxtojR1kHjK7bgoIkKixbWOd49zWehIO3mjINLTeWKQLmgpeZ8t6NHJ3P/cpm0eeF/ysPETiKj2lrcks5U2gAsecYZ425x2XWAeDLqjULVGR0Fk65SFzkvuEwI4I6+6ddk7bwZ+LNBiDpCrVHHRAVR5GFJbSKYUBNPyZOSzAX+RQVCsirXZa6GRmFvugEhrBn39iKvf3nKrfxhdUJEg+HFXitx+KDjF1xTKErGaX2JRtFm420VfUhi5KRiz/Fo3PV3rz4sF42yv9E58YS50w/YNloleXJF5veUCB1gN2ZodYtVuKfyPXu+1wOJwdX0hsylHbkaQ4KgLKB3moHz8/BuOIUjcL5lyIS5F95IqW+W3t4BCOoM/28DRyxy6ZNPN9ffJ2WLs1qo+NjHjXUsyoYDhesK0eHvZkHEon82NH/En9Ah5FArgidFAty8vatGdzyb1PImoWGPmZRHwZ+rx2ZBW0o5WGmiNWDmEya1HQEWFXE3bRvSUlUTi7k3ONdXS2kIQ3JnjNTt5HRLS5ZJpZcK3HtCr9u0EVeQeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
